### ISSUE TITLE
SDR# v1.0.0.1426 & plugin - no start?

### ISSUE THREAD

**Issue by sm3ulc** [sergionavarrog/RDSOutput#1]
I'm using SDR# v1.0.0.1426 and have added line to plugins.xml. Cannot se listening port with netstat -a and no sign in the sidebar either. Should there be something in the sidebar?

// David

**Comment by sergionavarrog** [comment]
v1.0.0.1426 is an old version, try my old RDSOutput.dll version.
I deleted the file RDSOutput.dll because is not valid for new SDR# versions.
You can find the old RDSOutput.dll in the commits section.
And, yes, the plugin window should be displayed in the sidebar.

**Comment by sergionavarrog** [comment]
You were right. I have uploaded a new file. Thanks for your help.

**Comment by andimik** [comment]
I have the same problem, but I'm using the latest 1.0.0.1490. Your plug-in does not appear in the sidebar. Is there any SDR# Version working?

**Comment by sergionavarrog** [comment]
I tried with 1.0.0.1491 and works fine. See screen capture on README.md. Tested with Windows 7 32 bits.  Let me know what is your operative system if the problem persists. Thanks for the feedback.
