### ISSUE TITLE
connection not working in newer SDR version? 

### ISSUE THREAD

**Issue by andimik** [sergionavarrog/RDSOutput#2]
It worked weeks ago. In the meanwhile I've updated to SDR 1.0.0.1573 and also updated to Win 10 17.03

Now I have connected and disconnected all the time.

Rdsspy is working well with another program through localhost:23

The dll is 1.0.6105.32267

**Comment by andimik** [comment]
Same with 1577 ...

**Comment by sergionavarrog** [comment]
Please, check out the new dll commit for me. I don't have Windows 10.

**Comment by andimik** [comment]
Yes, confirmed. This new dll works well. :-)
